changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
  categories:
    - title: User-facing improvements
      labels:
        - enhancement
        - accessibility
        - performance
    - title: Correctness fixes
      labels:
        - bug
        - data-integrity
    - title: Maintenance
      labels:
        - dependencies
        - automation
        - documentation
    - title: Other changes
      labels:
        - "*"
